on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{ secrets.REPO_GH_PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        if: steps.release.outputs.paths_released != '[]'
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        if: steps.release.outputs.paths_released != '[]'
        with:
          node-version: '22.14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        if: steps.release.outputs.paths_released != '[]'
        run: |
          npm install
          npm run build
          npm run verify:build
      - name: Publish
        if: steps.release.outputs.paths_released != '[]'
        run: |
          npm run publish-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
